//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindKeeper.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public int EntityID { get; set; }
        public int NoteID { get; set; }
        public string EntityType { get; set; }
        public string EntityValue { get; set; }
        public Nullable<int> PositionStart { get; set; }
        public Nullable<int> PositionEnd { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
