//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindKeeper.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public int ReminderID { get; set; }
        public int NoteID { get; set; }
        public System.DateTime ReminderDate { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> NotifiedAt { get; set; }
    
        public virtual Note Note { get; set; }
    }
}
